### ISSUE TITLE
New component: button dropdown

### ISSUE THREAD

**Issue by stefanomacconi** [smeup/ketchup#635]
As requested by Eusebiu.
See:
- https://valor-software.com/ngx-bootstrap/#/dropdowns
- on the workflow we need https://valor-software.com/ngx-bootstrap/#/dropdowns#split-button

![image](https://user-images.githubusercontent.com/30345093/100898255-d82b1780-34c0-11eb-902b-b7031ca07dc8.png)

**Comment by pasere-smeup** [comment]
Close #738
