### ISSUE TITLE
kup-text-field contained in kup-data-table

### ISSUE THREAD

**Issue by pasere-smeup** [smeup/ketchup#777]
On remove a row containting a text-field having a value, the value is "recycled" for the new row, which should have text-field with value empty: see attached .gif (https://trello-attachments.s3.amazonaws.com/5f7478099d04e94aae2d89b7/5fe9b1c76729d8327133eaeb/5e6c427479e1245ed0260982d7e31e0c/B4Eh4BMRTt.gif)

**Comment by foscili-smeup** [comment]
Closed with #921
